import type { CSSProperties } from "react";
import type { CcChain, CcInterval, DefensiveOverlap, DrOverlap, ParticipantDetails, TimelineEvent } from "../types";
import { healerSpecializations } from "../types";
import { formatDuration } from "../utils/formatting";

function isAllowedDefensiveCombination(firstSpell: string, secondSpell: string): boolean { const spells = new Set([firstSpell.toLowerCase().trim(), secondSpell.toLowerCase().trim()]); return spells.size === 2 && spells.has("phase shift") && spells.has("fade"); }
function isIgnoredDefensiveOverlapSpell(spell: string, spellId: number): boolean { const name = spell.toLowerCase().trim(); return name.includes("phase shift") || name === "fade" || name.includes("frenzied regeneration") || name.includes("sanctified ground") || name.includes("precognition") || name.includes("spirit of redemption") || name.includes("gladiator's medallion") || name.includes("pvp trinket") || name === "trinket" || spellId === 336126 || spellId === 208683 || spellId === 42292; }

export function timelineEventTeam(event: TimelineEvent, participants: ParticipantDetails[]): number | null { return participants.find((participant) => participant.name === event.source)?.team ?? event.team; }
function timelineTargetLabel(event: TimelineEvent, participants: ParticipantDetails[]): string { const target = event.target == null ? null : participants.find((participant) => participant.name === event.target); if (target == null) return event.target ?? event.source; if (healerSpecializations.has(target.specializationName)) return "healer"; return (target.className ?? target.name).toLowerCase(); }
function timelineTargetsLabel(event: TimelineEvent, relatedEvents: TimelineEvent[], participants: ParticipantDetails[]): string { const labels = relatedEvents.filter((candidate) => candidate.spellId === event.spellId && candidate.source === event.source && candidate.target != null && Math.abs(candidate.offsetSeconds - event.offsetSeconds) < 0.5).map((candidate) => timelineTargetLabel(candidate, participants)); if (labels.length === 0) return timelineTargetLabel(event, participants); const counts = new Map<string, number>(); labels.forEach((label) => counts.set(label, (counts.get(label) ?? 0) + 1)); return Array.from(counts, ([label, count]) => count > 1 ? `${label} ×${count}` : label).join(", "); }
export function timelineEventDescription(event: TimelineEvent, relatedEvents: TimelineEvent[], participants: ParticipantDetails[]): string { if (event.eventType === "UNIT_DIED") return `${event.target ?? event.source} died at ${formatDuration(event.offsetSeconds)}`; return `${event.spell} → ${timelineTargetsLabel(event, relatedEvents, participants)}`; }

export function deduplicateTimelineEvents(events: TimelineEvent[]): TimelineEvent[] { const groups: TimelineEvent[][] = []; events.forEach((event) => { const group = groups.find((candidates) => { const previous = candidates[0]; return previous.source === event.source && previous.spell.toLowerCase() === event.spell.toLowerCase() && Math.abs(previous.offsetSeconds - event.offsetSeconds) < 0.5; }); if (group) group.push(event); else groups.push([event]); }); return groups.map((group) => group.find((event) => event.eventType === "SPELL_CAST_SUCCESS") ?? group[0]); }
export function timelineWithStoredDeaths(events: TimelineEvent[], participants: ParticipantDetails[]): TimelineEvent[] { const combined = [...events]; participants.forEach((player) => (player.deathRecaps ?? []).forEach((recap) => { const alreadyIncluded = combined.some((event) => event.eventType === "UNIT_DIED" && event.target === player.name && event.offsetSeconds === recap.offsetSeconds); if (!alreadyIncluded) combined.push({ offsetSeconds: recap.offsetSeconds, spellId: 0, spell: "Died", category: "DEATH", source: player.name, team: player.team, target: player.name, eventType: "UNIT_DIED" }); })); return combined.sort((first, second) => first.offsetSeconds - second.offsetSeconds); }
export function timelineStackIndex(events: TimelineEvent[], eventIndex: number, sideFor: (event: TimelineEvent) => number, collisionWindowSeconds: number): number { const event = events[eventIndex]; const side = sideFor(event); return events.slice(0, eventIndex).filter((candidate) => sideFor(candidate) === side && Math.abs(candidate.offsetSeconds - event.offsetSeconds) <= collisionWindowSeconds).length % 3; }
export function timelineEventStyle(left: string, stackIndex: number): CSSProperties { return { left, "--timeline-stack-offset": `${stackIndex * 17}px` } as CSSProperties; }

export function drCategory(spell: string): string { const name = spell.toLowerCase(); if (["kidney shot", "cheap shot", "hammer of justice", "leg sweep", "maim", "mighty bash", "storm bolt", "asphyxiate", "shadowfury", "axe toss"].some((value) => name.includes(value))) return "Stun"; if (["cyclone", "fear", "psychic scream", "howl of terror", "intimidating shout"].some((value) => name.includes(value))) return "Disorient"; if (["polymorph", "sap", "repentance", "paralysis", "freezing trap", "hex", "imprison", "gouge", "mortal coil"].some((value) => name.includes(value))) return "Incapacitate"; if (["frost nova", "entangling roots", "mass entanglement"].some((value) => name.includes(value))) return "Root"; if (["silence", "garrote"].some((value) => name.includes(value))) return "Silence"; return spell; }
function defensiveOwner(event: TimelineEvent): string | null { if (event.spell.toLowerCase().includes("touch of karma")) return event.source || null; return event.target; }
export function defensiveOverlaps(events: TimelineEvent[]): DefensiveOverlap[] { const applications = events.filter((event) => event.category === "DEFENSIVE" && event.eventType === "SPELL_AURA_APPLIED" && defensiveOwner(event)); const removals = events.filter((event) => event.category === "DEFENSIVE" && event.eventType === "SPELL_AURA_REMOVED" && defensiveOwner(event)); const usedRemovals = new Set<number>(); const intervals = applications.flatMap((event) => { const owner = defensiveOwner(event); const removalIndex = removals.findIndex((removal, index) => !usedRemovals.has(index) && defensiveOwner(removal) === owner && removal.offsetSeconds >= event.offsetSeconds && (removal.spellId === event.spellId || removal.spell === event.spell)); if (removalIndex < 0) return []; usedRemovals.add(removalIndex); return [{ target: owner!, spell: event.spell, spellId: event.spellId, start: event.offsetSeconds, end: removals[removalIndex].offsetSeconds }]; }); const overlaps: DefensiveOverlap[] = []; intervals.forEach((first, index) => intervals.slice(index + 1).forEach((second) => { const start = Math.max(first.start, second.start); const end = Math.min(first.end, second.end); if (first.target === second.target && first.spell !== second.spell && start < end && !isIgnoredDefensiveOverlapSpell(first.spell, first.spellId) && !isIgnoredDefensiveOverlapSpell(second.spell, second.spellId) && !isAllowedDefensiveCombination(first.spell, second.spell)) overlaps.push({ target: first.target, first: first.spell, firstSpellId: first.spellId, second: second.spell, secondSpellId: second.spellId, start, end }); })); return overlaps; }

export function ccIntervalsFor(target: ParticipantDetails, events: TimelineEvent[], duration: number): CcInterval[] { const removals = events.filter((event) => event.category === "CROWD_CONTROL" && event.eventType === "SPELL_AURA_REMOVED" && event.target === target.name); const usedRemovals = new Set<number>(); const intervals = events.filter((event) => event.category === "CROWD_CONTROL" && event.eventType === "SPELL_AURA_APPLIED" && event.target === target.name).map((event): CcInterval => { const removalIndex = removals.findIndex((removal, index) => !usedRemovals.has(index) && removal.offsetSeconds >= event.offsetSeconds && (removal.spellId === event.spellId || removal.spell === event.spell)); if (removalIndex >= 0) usedRemovals.add(removalIndex); const exactDuration = removalIndex >= 0; return { start: event.offsetSeconds, end: exactDuration ? removals[removalIndex].offsetSeconds : Math.min(duration, event.offsetSeconds + 1), spellId: event.spellId, spell: event.spell, source: event.source, exactDuration, lane: 0, drCategory: drCategory(event.spell), previousDrEnd: null, previousDrSpell: null, previousDrSpellId: null, drGap: null }; }).sort((first, second) => first.start - second.start || first.end - second.end); intervals.forEach((interval, index) => { const occupied = new Set(intervals.slice(0, index).filter((previous) => previous.end > interval.start).map((previous) => previous.lane)); while (occupied.has(interval.lane)) interval.lane++; }); const previousByCategory = new Map<string, CcInterval>(); intervals.forEach((interval) => { const previous = previousByCategory.get(interval.drCategory); if (previous && interval.start - previous.end <= 18) { interval.previousDrEnd = previous.end; interval.previousDrSpell = previous.spell; interval.previousDrSpellId = previous.spellId; interval.drGap = interval.start - previous.end; } if (!previous || interval.end >= previous.end) previousByCategory.set(interval.drCategory, interval); }); return intervals; }
export function drOverlaps(participants: ParticipantDetails[], events: TimelineEvent[], duration: number): DrOverlap[] { return participants.flatMap((target) => { const intervals = ccIntervalsFor(target, events, duration); const reducedApplications: DrOverlap[] = intervals.filter((interval) => interval.drGap != null && interval.previousDrEnd != null).map((interval) => ({ target, first: interval.previousDrSpell ?? "Previous CC", firstSpellId: interval.previousDrSpellId ?? 0, second: interval.spell, secondSpellId: interval.spellId, category: interval.drCategory, start: interval.start, end: Math.max(interval.start + 0.5, interval.end), gap: interval.drGap!, immune: false })); const immuneAttempts: DrOverlap[] = events.filter((event) => event.category === "CROWD_CONTROL" && event.eventType === "SPELL_MISSED" && event.target === target.name).flatMap((event) => { const category = drCategory(event.spell); const previous = intervals.filter((interval) => interval.drCategory === category && interval.start <= event.offsetSeconds && event.offsetSeconds - interval.end <= 18).at(-1); if (!previous) return []; return [{ target, first: previous.spell, firstSpellId: previous.spellId, second: event.spell, secondSpellId: event.spellId, category, start: event.offsetSeconds, end: event.offsetSeconds + 0.5, gap: event.offsetSeconds - previous.end, immune: true }]; }); return [...reducedApplications, ...immuneAttempts]; }).sort((first, second) => first.start - second.start); }
export function isPvpTrinket(event: TimelineEvent): boolean { return event.spellId === 336126 || event.spellId === 208683 || event.spellId === 42292 || event.spell.toLowerCase().includes("gladiator's medallion"); }
export function ccChains(intervals: CcInterval[], trinkets: TimelineEvent[]): CcChain[] { const chains: CcChain[] = []; intervals.forEach((interval) => { const current = chains.at(-1); const interruptedBeforeNextCc = current && trinkets.some((trinket) => trinket.offsetSeconds >= current.start && trinket.offsetSeconds <= interval.start); if (current && interval.start <= current.end && !interruptedBeforeNextCc) { current.end = Math.max(current.end, interval.end); current.totalDuration = Math.max(0, current.end - current.start); current.exactDuration = current.exactDuration && interval.exactDuration; } else chains.push({ start: interval.start, end: interval.end, totalDuration: Math.max(0, interval.end - interval.start), exactDuration: interval.exactDuration, trinket: null }); }); chains.forEach((chain) => { chain.trinket = trinkets.find((trinket) => trinket.offsetSeconds >= chain.start && trinket.offsetSeconds <= chain.end + 1) ?? null; }); return chains; }
export function personalTimelineEvents(player: ParticipantDetails, events: TimelineEvent[]): TimelineEvent[] { return deduplicateTimelineEvents(events.filter((event) => (event.eventType === "UNIT_DIED" && event.target === player.name) || (event.source === player.name && (event.eventType === "SPELL_CAST_SUCCESS" || event.eventType === "SPELL_AURA_APPLIED")) || (event.target === player.name && event.eventType === "SPELL_AURA_APPLIED"))); }
